version: 2

jobs:
  test-app:
    docker:
      - image: paszser/comparerapp:latest
    steps:
      - run: apt-get update && apt-get install -y openssh-client git
      - checkout
      - run:
          name: "Task para app test"
          command: "rake test"

workflows:
  version: 2
  test-app-workflow:
    jobs:
      - test-app 